### ISSUE TITLE
Exception while executing circuit shown on  SpiceSharpGUI/screenshots/screen02.png 

### ISSUE THREAD

**Issue by a3an-de** [SpiceSharp/SpiceSharpGUI#23]
While executing the above circuit, an exception is thrown while parsing the expression mc(0.6,tol) of line 3.
   at SpiceSharpGUI.Windows.ViewModels.NetlistResultWindowViewModel.RunSimulations() in C:\Users\a-sch\Downloads\SpiceSharpGUI-master\SpiceSharpGUI-master\src\windows\SpiceSharpGUI.Windows\ViewModels\NetlistResultWindowViewModel.cs:line 217  

I have been trying to run  SpiceSharpParser/src/SpiceSharpParser.IntegrationTests/Resources/example01.cir.  
It uses an interesting feature like .func, it does run but does not produce any output.
Does anybody have a meaningful .plot statement for this circuit ?

Thanks, Adrian

**Comment by marcin-golebiowski** [comment]
I will look in a moment. I will reply soon.

**Comment by marcin-golebiowski** [comment]
@a3an-de  I've checked the circuit from screen02 and it works for me after I've downloaded the SpiceSharpGUI from master branch and compiled it.
Are you put the expression in curly brackets?

Example01.cir comes from some users of SpiceSharp/SharpParser that ageed that I could include it in the tests to validate that the library is able to parse that circuit.
The circuits uses .SAVE statement. It allows to access values in code.

To see it in SpiceSharpGUID you please change `.SAVE V(N1) V(N2) V(N3)` to `.PRINT V(N1) V(N2) V(N3)`

If there is any help you need, don't hesitate to ask.

**Comment by a3an-de** [comment]
this is the circuit:
V1 IN 0 AC 1 
L1 IN MIDDLE {mc (0.6, tol)} 
C1 MIDDLE OUT {mc (10e-6, tol)} 
R1 OUT 0 {mc (1000, tol)} 
.ac oct 100 1 500 
.step param X 0 10 1 
.param tol = 0.2 
.plot ac v (OUT) merge 
.end

I have to admit that I am not very fluent in c# nor in the usage of MS Visual Studio. A short script on how to setup SpiceSharpGUI in VS and howto run a proven circuit would be useful. 

Adrian

**Comment by marcin-golebiowski** [comment]
@a3an-de  Do you need any help? 

Kind regards,
Marcin

**Comment by a3an-de** [comment]
Hi Marcin,

I did reinstall spicesharpgui again,  it did not help.
I noticed that the .csproj file indicates a back level version of the spicesharpparser library 1.4.3, not 1.5.0.
Could that be the reason ? How would I change that ?

Regards, Adrian 

Von meinem iPad gesendet

> Am 16.05.2020 um 21:33 schrieb Marcin <notifications@github.com>:
> 

﻿
@a3an-de Do you need any help?

Kind regards,
Marcin

**Comment by marcin-golebiowski** [comment]
I will update the project to use 1.5.0 in few minutes.
Thank you for information

**Comment by marcin-golebiowski** [comment]
I've updated it to use latest version of SpiceSharpParser.
I've verifed iit and I'm getting the plots as below:

![obraz](https://user-images.githubusercontent.com/115426/82146632-f34b7800-984b-11ea-8a28-dedb625a771f.png)

I've updated the file with circuit that you are trying to simulate.
https://github.com/SpiceSharp/SpiceSharpGUI/blob/master/screenshots/band-pass.cir

**Comment by a3an-de** [comment]
@marcin-golebiowski  I noticed a subtle difference between my version and your version of the circuit. My version has a space between 'mc' and '(' like 'mc (', yours does not like 'mc('. 
After removing the spaces the problem is gone.  We might call this an bug in spicesharpparser.

The more important the problem of the spicesharpparser version is, it might have been fixed with version 1.5.0.
The .csproj file still indicates a back level version of the spicesharpparser library 1.4.3, not 1.5.0. 
You can easily see this by using the code browser on the github project website. 

Regards, Adrian

**Comment by marcin-golebiowski** [comment]
@a3an-de I will take a look at the issue with space.

I forgot to push the commit to github. Sorry about that. It should be fine now.

Marcin

**Comment by a3an-de** [comment]
@marcin-golebiowski Ok, 1.5.0 is active. 
However, I got a weird problem. When running test1.cir every thing looks ok, this is the circuit without an embedded blank in the first mc() call.

![test1](https://user-images.githubusercontent.com/33397128/82215486-c82e5a80-9917-11ea-80ce-b5e2f027dbf0.png)

When I run test2.cir I get a different curve, this is the circuit with an embedded blank in the first mc() call.

![test2](https://user-images.githubusercontent.com/33397128/82215899-5d315380-9918-11ea-9aa6-04883e086674.png)

when I insert a blank in all mc() calls, I get an exception.
   at SpiceSharpGUI.Windows.ViewModels.NetlistResultWindowViewModel.RunSimulations() in C:\Users\a-sch\source\repos\SpiceSharpGUI\src\windows\SpiceSharpGUI.Windows\ViewModels\NetlistResultWindowViewModel.cs:line 227
---> (Inner Exception #0) SpiceSharp.CircuitException: No model specified

By the way, what is mc() doing ?

Regards, Adrian

**Comment by marcin-golebiowski** [comment]
@a3an-de  I will take a look tomorrow.

The souce code of `mc` is available at:

https://github.com/SpiceSharp/SpiceSharpParser/blob/master/src/SpiceSharpParser/ModelReaders/Netlist/Spice/Evaluation/Functions/Random/McFunction.cs

**Comment by a3an-de** [comment]
Hi Marcin,

I have been offline for some time and unable to track this issue.
I was trying to find out the status of this problem, I could not find 
any information about this issue at all.

Could you tell me how this issue was resolved ?

Regards, Adrian


-------- Forwarded Message --------
Subject: 	Re: [SpiceSharp/SpiceSharpGUI] Exception while executing 
circuit shown on SpiceSharpGUI/screenshots/screen02.png (#23)
Date: 	Sun, 17 May 2020 14:15:54 +0200
From: 	Adrian Schuur <a-schuur@netcom-mail.de>
To: 	SpiceSharp/SpiceSharpGUI 
<reply@reply.github.com>



Hi Marcin,

I did reinstall spicesharpgui again,  it did not help.
I noticed that the .csproj file indicates a back level version of the 
spicesharpparser library 1.4.3, not 1.5.0.
Could that be the reason ? How would I change that ?

Regards, Adrian

Von meinem iPad gesendet

> Am 16.05.2020 um 21:33 schrieb Marcin <notifications@github.com>:
>
﻿

@a3an-de <https://github.com/a3an-de> Do you need any help?

Kind regards,
Marcin

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
<https://github.com/SpiceSharp/SpiceSharpGUI/issues/23#issuecomment-629695665>, 
or unsubscribe

**Comment by marcin-golebiowski** [comment]
Hello,

Sorry for the delay and no information about the status.
I'm very busy at the moment but I will look at this issue as soon as possible.

With kind regards,
Marcin

**Comment by marcin-golebiowski** [comment]
It's fixed in latest SpiceSharpGUI.
Sorry for not responding.
